domain_name: lab.local
login_user: admin
login_role: 15

# VLAN
vlans:
  - { id: 10, name: USERS10 }
  - { id: 20, name: USERS20 }
  - { id: 99, name: MGMT }

# L2 mgmt (svitsjer i VLAN99)
l2_mgmt:
  sw0: { ip: 192.168.99.2, mask: 255.255.255.0, gw: 192.168.99.1 }
  sw1: { ip: 192.168.99.3, mask: 255.255.255.0, gw: 192.168.99.1 }
  sw2: { ip: 192.168.99.4, mask: 255.255.255.0, gw: 192.168.99.1 }
  sw3: { ip: 192.168.99.5, mask: 255.255.255.0, gw: 192.168.99.1 }

# Eksempelporter (tilpass til labben)
access_ports_v10:
  - { name: GigabitEthernet0/1, vlan: 10 }
access_ports_v20:
  - { name: GigabitEthernet0/2, vlan: 20 }
trunks:
  - { name: GigabitEthernet0/24, allowed: "10,20,99" }

# MLS SVI-er
mls_svis:
  - { vlan: 10, ip: 10.10.10.1, mask: 255.255.255.0 }
  - { vlan: 20, ip: 10.10.20.1, mask: 255.255.255.0 }
  - { vlan: 99, ip: 192.168.99.1, mask: 255.255.255.0 }

# MLS routed uplinks (bytt interfacenavn til dine uplinks)
mls_routed_uplinks:
  - { name: GigabitEthernet1/1, ip: 10.255.0.2, mask: 255.255.255.252, next_hop: 10.255.0.1 }  # til R0
  - { name: GigabitEthernet1/2, ip: 10.255.0.6, mask: 255.255.255.252, next_hop: 10.255.0.5 }  # til R1

# MLS default routes (primær + backup)
mls_default_routes:
  - { dest: 0.0.0.0/0, next_hop: 10.255.0.1, distance: 1 }
  - { dest: 0.0.0.0/0, next_hop: 10.255.0.5, distance: 5 }

# Router IF-er mot MLS
r0_if: { name: GigabitEthernet0/0, ip: 10.255.0.1, mask: 255.255.255.252 }
r1_if: { name: GigabitEthernet0/0, ip: 10.255.0.5, mask: 255.255.255.252 }

# Returruter (via MLS) – brukes på R0/R1
router_returns:
  - { dest: 10.10.10.0/24, next_hop: 10.255.0.2 }
  - { dest: 10.10.20.0/24, next_hop: 10.255.0.2 }
  - { dest: 192.168.99.0/24, next_hop: 10.255.0.2 }

# DHCP (på R0)
dhcp_pools:
  - name: VLAN10_POOL
    network: 10.10.10.0 255.255.255.0
    default_router: 10.10.10.1
    dns: 1.1.1.1
    excluded:
      - { start: 10.10.10.1, end: 10.10.10.20 }
  - name: VLAN20_POOL
    network: 10.10.20.0 255.255.255.0
    default_router: 10.10.20.1
    dns: 1.1.1.1
    excluded:
      - { start: 10.10.20.1, end: 10.10.20.20 }
