---
- name: Base (hostname, domain, user, SSH)
  hosts: all
  gather_facts: no
  tasks:
    - name: Hostname + domain
      cisco.ios.ios_config:
        lines:
          - "hostname {{ hostname | default(inventory_hostname) }}"
          - "ip domain-name {{ domain_name }}"

    - name: Local admin user present
      cisco.ios.ios_user:
        name: "{{ login_user }}"
        privilege: "{{ login_role }}"
        configured_password: "{{ ansible_password }}"
        state: present

    - name: SSH v2 + RSA key
      cisco.ios.ios_config:
        lines:
          - ip ssh version 2
          - crypto key generate rsa modulus 2048

    - name: VTY login local + ssh only
      cisco.ios.ios_config:
        parents: line vty 0 15
        lines:
          - login local
          - transport input ssh
          - exec-timeout 10 0

    - name: Basic hardening
      cisco.ios.ios_config:
        lines:
          - no ip http server
          - no ip http secure-server
          - service password-encryption
