---
- name: L2: VLAN + porter + mgmt SVI
  hosts: switches_l2
  gather_facts: no
  tasks:
    - name: Ensure VLANs
      cisco.ios.ios_vlans:
        config: "{{ vlans | map('combine', {'state':'active'}) | list }}"
        state: merged

    - name: Access ports v10
      when: access_ports_v10 is defined
      cisco.ios.ios_l2_interfaces:
        config: "{{ access_ports_v10 | map('combine', {'mode':'access'}) | list }}"
        state: merged

    - name: Access ports v20
      when: access_ports_v20 is defined
      cisco.ios.ios_l2_interfaces:
        config: "{{ access_ports_v20 | map('combine', {'mode':'access'}) | list }}"
        state: merged

    - name: Tag access + no shut
      when: (access_ports_v10|default([])) or (access_ports_v20|default([]))
      cisco.ios.ios_config:
        with_items: "{{ (access_ports_v10|default([])) + (access_ports_v20|default([])) }}"
        loop_control: { loop_var: p }
        parents: "interface {{ p.name }}"
        lines:
          - "switchport access vlan {{ p.vlan }}"
          - "spanning-tree portfast"
          - "no shutdown"

    - name: Trunks
      when: trunks is defined
      cisco.ios.ios_config:
        with_items: "{{ trunks }}"
        loop_control: { loop_var: t }
        parents: "interface {{ t.name }}"
        lines:
          - switchport mode trunk
          - "switchport trunk allowed vlan {{ t.allowed }}"
          - no shutdown

    - name: Mgmt SVI Vlan99 + default-gw
      cisco.ios.ios_config:
        lines:
          - "interface Vlan99"
          - " ip address {{ l2_mgmt[inventory_hostname].ip }} {{ l2_mgmt[inventory_hostname].mask }}"
          - " no shutdown"
          - "exit"
          - "ip default-gateway {{ l2_mgmt[inventory_hostname].gw }}"
