---
- name: R0: L3 mot MLS + DHCP + returruter
  hosts: r0
  gather_facts: no
  tasks:
    - name: R0 interface mot MLS
      cisco.ios.ios_config:
        parents: "interface {{ r0_if.name }}"
        lines:
          - "ip address {{ r0_if.ip }} {{ r0_if.mask }}"
          - "no shutdown"

    - name: R0: Returruter via MLS
      cisco.ios.ios_config:
        with_items: "{{ router_returns }}"
        loop_control: { loop_var: rt }
        lines:
          - "ip route {{ rt.dest.split('/')[0] }} {{ (rt.dest.split('/')[1]|int)|ipaddr('netmask') }} {{ rt.next_hop }}"

    - name: R0: DHCP excluded
      cisco.ios.ios_config:
        with_items: "{{ dhcp_pools | map(attribute='excluded') | list | sum(start=[]) }}"
        loop_control: { loop_var: ex }
        lines:
          - "ip dhcp excluded-address {{ ex.start }} {{ ex.end }}"

    - name: R0: DHCP pools
      cisco.ios.ios_config:
        with_items: "{{ dhcp_pools }}"
        loop_control: { loop_var: p }
        lines:
          - "ip dhcp pool {{ p.name }}"
          - "network {{ p.network }}"
          - "default-router {{ p.default_router }}"
          - "dns-server {{ p.dns }}"

- name: R1: L3 mot MLS + returruter (ingen DHCP)
  hosts: r1
  gather_facts: no
  tasks:
    - name: R1 interface mot MLS
      cisco.ios.ios_config:
        parents: "interface {{ r1_if.name }}"
        lines:
          - "ip address {{ r1_if.ip }} {{ r1_if.mask }}"
          - "no shutdown"

    - name: R1: returruter via MLS (next-hop = 10.255.0.6)
      cisco.ios.ios_config:
        with_items: "{{ router_returns | map('combine', {'next_hop':'10.255.0.6'}) | list }}"
        loop_control: { loop_var: rt }
        lines:
          - "ip route {{ rt.dest.split('/')[0] }} {{ (rt.dest.split('/')[1]|int)|ipaddr('netmask') }} {{ rt.next_hop }}"
